### numpy sample

In [4]:
import  numpy as np 
my_arr = np.arange(1000000)

In [3]:
my_list = list(range(1000000))

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 19 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.03 s


### ndarray
N-dimensional array 

In [14]:
import numpy as np
data = np.random.randn(2, 3)
data

array([[-0.22551473,  1.32962824, -1.30678736],
       [ 0.34871752,  0.24949911,  0.34061014]])

In [15]:
data * 10 

array([[ -2.25514728,  13.29628235, -13.06787361],
       [  3.48717517,   2.49499114,   3.40610143]])

In [16]:
data + data

array([[-0.45102946,  2.65925647, -2.61357472],
       [ 0.69743503,  0.49899823,  0.68122029]])

In [17]:
data * data

array([[0.05085689, 1.76791124, 1.70769321],
       [0.12160391, 0.06224981, 0.11601527]])

In [18]:
data.shape

(2, 3)

In [19]:
data.dtype

dtype('float64')

In [ ]:
### create ndarrays 

#### array 
create NumPy array from any sequence

In [21]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
arr2.ndim

2

In [24]:
arr2.shape

(2, 4)

In [25]:
arr1.dtype

dtype('float64')

In [26]:
arr2.dtype

dtype('int32')

#### zeros
create arrays of 0s

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

#### ons
create arrays of 1s

In [30]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [31]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

#### arange
 returns an ndarray  from range

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

#### empty
Create new arrays by allocating new memory, but do not populate with any values like ones and

In [33]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### data type 
dtype of np array 

In [36]:
arr1 = np.array([1,2,3],dtype=np.float64)
arr1.dtype

dtype('float64')

In [37]:
arr2 = np.array([1,2,3],dtype = np.int32)
arr2.dtype

dtype('int32')

In [38]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [39]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [40]:
float_arr

array([1., 2., 3., 4., 5.])

In [41]:
numertic_strinsgs = np.array(['1.25', '-9.6', '42'], dtype=np.float64)
numertic_strinsgs

array([ 1.25, -9.6 , 42.  ])

In [42]:
numertic_strinsgs.dtype

dtype('float64')

In [44]:
numertic_strinsgs.astype(np.float64)

array([ 1.25, -9.6 , 42.  ])

### Arithmetic

In [47]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [49]:
arr - arr

array([[0, 0, 0],
       [0, 0, 0]])

In [50]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [51]:
arr ** 0.5 

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [53]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [54]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### index and slicing

In [56]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
arr[5]

5

In [58]:
arr[5:8]

array([5, 6, 7])

In [59]:
arr[5:8] = 12  
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [60]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [63]:
arr_slice[1] = 12345
arr_slice

array([   12, 12345,    12])

In [64]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [66]:
arr_slice[:] = 64
arr_slice

array([64, 64, 64])

In [67]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [68]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr2d  

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [69]:
arr2d[2]

array([7, 8, 9])

In [70]:
arr2d[0][2]

3

In [71]:
arr2d[0,2]

3

In [72]:
arr3d =  np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [73]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [74]:
old_values = arr3d[0].copy()

In [75]:
arr3d[0] = 42

In [76]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [77]:
arr3d[0] = old_values

In [78]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[1,0]

array([7, 8, 9])

In [80]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [81]:
x[0]

array([7, 8, 9])

In [82]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [83]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [84]:
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [87]:
arr2d[1, :2]

array([4, 5])

In [89]:
arr2d[:2, 2]

array([3, 6])

In [90]:
arr2d[:, :1]

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [91]:
arr2d[:2, 1:] = 0
arr2d

array([[ 1,  0,  0],
       [ 4,  0,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

In [94]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [95]:
data

array([[-0.14395058, -0.45912247, -0.23095212,  0.7252082 ],
       [ 0.16801606,  0.39915783, -0.79745618,  0.44211503],
       [-0.31108888, -2.64369723, -0.58062369, -0.42243279],
       [-1.13428175,  0.88255072,  0.76300057,  1.1394058 ],
       [-0.43746088,  0.58811724,  1.14490366,  2.60127222],
       [-1.05635597, -1.15091627,  0.61414603,  0.57451848],
       [-0.27261721, -0.89973522,  0.45317707,  0.90367475]])

In [96]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [97]:
data[names == 'Bob']

array([[-0.14395058, -0.45912247, -0.23095212,  0.7252082 ],
       [-1.13428175,  0.88255072,  0.76300057,  1.1394058 ]])

In [98]:
data[[ True, False, False,  True, False, False, False]]

array([[-0.14395058, -0.45912247, -0.23095212,  0.7252082 ],
       [-1.13428175,  0.88255072,  0.76300057,  1.1394058 ]])

In [99]:
data[names == 'Bob', 2:]

array([[-0.23095212,  0.7252082 ],
       [ 0.76300057,  1.1394058 ]])

In [100]:
data[names == 'Bob', 3]

array([0.7252082, 1.1394058])

In [101]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [102]:
data[~(names == 'Bob')]

array([[ 0.16801606,  0.39915783, -0.79745618,  0.44211503],
       [-0.31108888, -2.64369723, -0.58062369, -0.42243279],
       [-0.43746088,  0.58811724,  1.14490366,  2.60127222],
       [-1.05635597, -1.15091627,  0.61414603,  0.57451848],
       [-0.27261721, -0.89973522,  0.45317707,  0.90367475]])

In [103]:
cond = names == 'Bob'
data[~cond]

array([[ 0.16801606,  0.39915783, -0.79745618,  0.44211503],
       [-0.31108888, -2.64369723, -0.58062369, -0.42243279],
       [-0.43746088,  0.58811724,  1.14490366,  2.60127222],
       [-1.05635597, -1.15091627,  0.61414603,  0.57451848],
       [-0.27261721, -0.89973522,  0.45317707,  0.90367475]])

In [104]:
mask =(names == 'Bob') | (names == 'Will')
mask

array([ True, False,  True,  True,  True, False, False])

In [105]:
data[mask]

array([[-0.14395058, -0.45912247, -0.23095212,  0.7252082 ],
       [-0.31108888, -2.64369723, -0.58062369, -0.42243279],
       [-1.13428175,  0.88255072,  0.76300057,  1.1394058 ],
       [-0.43746088,  0.58811724,  1.14490366,  2.60127222]])

In [107]:
data[data < 0  ] = 0
data

array([[0.        , 0.        , 0.        , 0.7252082 ],
       [0.16801606, 0.39915783, 0.        , 0.44211503],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.88255072, 0.76300057, 1.1394058 ],
       [0.        , 0.58811724, 1.14490366, 2.60127222],
       [0.        , 0.        , 0.61414603, 0.57451848],
       [0.        , 0.        , 0.45317707, 0.90367475]])

In [109]:
data[names != 'Joe'] = 7
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.16801606, 0.39915783, 0.        , 0.44211503],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 0.61414603, 0.57451848],
       [0.        , 0.        , 0.45317707, 0.90367475]])

In [ ]:
### Fancy Indexing

In [110]:
arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr[[4, 3, 0, 6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [112]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [114]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [115]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

### Transposing Arrays

In [116]:
arr = np.arange(15).reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [118]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [120]:
arr = np.random.randn(6, 3)
arr

array([[-0.21587396, -0.95452912,  0.78045953],
       [ 0.22174203, -0.46396227, -1.13186748],
       [-0.65492986, -1.28278528, -0.38373618],
       [-0.67336008, -0.21979618,  0.96383192],
       [ 0.85451878,  0.3540906 ,  0.02777749],
       [ 0.89976606, -0.36356555, -0.36525266]])

In [122]:
arr.T

array([[-0.21587396,  0.22174203, -0.65492986, -0.67336008,  0.85451878,
         0.89976606],
       [-0.95452912, -0.46396227, -1.28278528, -0.21979618,  0.3540906 ,
        -0.36356555],
       [ 0.78045953, -1.13186748, -0.38373618,  0.96383192,  0.02777749,
        -0.36525266]])

In [121]:
np.dot(arr.T, arr)

array([[ 2.51789933,  1.06676752, -1.1220547 ],
       [ 1.06676752,  3.07779531,  0.20320605],
       [-1.1220547 ,  0.20320605,  3.1006476 ]])

In [123]:
arr = np.arange(16).reshape((2, 2, 4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [124]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [133]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [127]:
arr.T

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [134]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [135]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

In [136]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

###  Universal Functions

In [137]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [138]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [139]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [149]:
x = np.random.randn(8)
y = np.random.randn(8)

In [150]:
x

array([ 0.34094311,  1.42714562,  0.98268304,  0.06337568, -1.34163963,
        0.25574231, -0.21193772,  0.30893144])

In [151]:
y

array([-0.19217842, -2.95264737,  0.44595614, -0.01990904, -0.6618892 ,
        0.99559637, -1.25440423, -2.87761853])

In [152]:
np.maximum(x, y)

array([ 0.34094311,  1.42714562,  0.98268304,  0.06337568, -0.6618892 ,
        0.99559637, -0.21193772,  0.30893144])

In [153]:
arr = np.random.randn(7) * 5
arr

array([ -3.2545259 ,  -1.76607456,   0.01739797, -11.36586476,
         2.79574902,   0.26591089,  11.42605172])

In [160]:
remainder, whole_part = np.modf(arr)

In [162]:
remainder

array([-0.2545259 , -0.76607456,  0.01739797, -0.36586476,  0.79574902,
        0.26591089,  0.42605172])

In [163]:
whole_part

array([ -3.,  -1.,   0., -11.,   2.,   0.,  11.])

In [164]:
arr

array([ -3.2545259 ,  -1.76607456,   0.01739797, -11.36586476,
         2.79574902,   0.26591089,  11.42605172])

In [165]:
np.sqrt(arr)

<ipython-input-165-b58949107b3d>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr)


array([       nan,        nan, 0.13190138,        nan, 1.67204935,
       0.51566548, 3.38024433])

In [166]:
np.sqrt(arr,arr)

<ipython-input-166-e3ca18b15869>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr,arr)


array([       nan,        nan, 0.13190138,        nan, 1.67204935,
       0.51566548, 3.38024433])

### Array-Oriented Programming

In [167]:
points = np.arange(-5, 5, 0.01)
points

array([-5.0000000e+00, -4.9900000e+00, -4.9800000e+00, -4.9700000e+00,
       -4.9600000e+00, -4.9500000e+00, -4.9400000e+00, -4.9300000e+00,
       -4.9200000e+00, -4.9100000e+00, -4.9000000e+00, -4.8900000e+00,
       -4.8800000e+00, -4.8700000e+00, -4.8600000e+00, -4.8500000e+00,
       -4.8400000e+00, -4.8300000e+00, -4.8200000e+00, -4.8100000e+00,
       -4.8000000e+00, -4.7900000e+00, -4.7800000e+00, -4.7700000e+00,
       -4.7600000e+00, -4.7500000e+00, -4.7400000e+00, -4.7300000e+00,
       -4.7200000e+00, -4.7100000e+00, -4.7000000e+00, -4.6900000e+00,
       -4.6800000e+00, -4.6700000e+00, -4.6600000e+00, -4.6500000e+00,
       -4.6400000e+00, -4.6300000e+00, -4.6200000e+00, -4.6100000e+00,
       -4.6000000e+00, -4.5900000e+00, -4.5800000e+00, -4.5700000e+00,
       -4.5600000e+00, -4.5500000e+00, -4.5400000e+00, -4.5300000e+00,
       -4.5200000e+00, -4.5100000e+00, -4.5000000e+00, -4.4900000e+00,
       -4.4800000e+00, -4.4700000e+00, -4.4600000e+00, -4.4500000e+00,
      

In [168]:
xs,ys = np.meshgrid(points, points)

In [169]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ...,
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [170]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [171]:
z = np.sqrt(xs ** 2 + ys ** 2)
z

array([[7.07106781, 7.06400028, 7.05693985, ..., 7.04988652, 7.05693985,
        7.06400028],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       ...,
       [7.04988652, 7.04279774, 7.03571603, ..., 7.0286414 , 7.03571603,
        7.04279774],
       [7.05693985, 7.04985815, 7.04278354, ..., 7.03571603, 7.04278354,
        7.04985815],
       [7.06400028, 7.05692568, 7.04985815, ..., 7.04279774, 7.04985815,
        7.05692568]])

In [ ]:
#### Expressing Conditional Logic

In [173]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [175]:
result = [(x if c else y)
          for x, y, c in zip(xarr, yarr, cond)]
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [176]:
result = np.where(cond, xarr, yarr)
result

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [177]:
arr = np.random.randn(4, 4)
arr

array([[ 0.96953676,  1.43733334, -0.67364028, -0.00315331],
       [-0.0094574 , -0.10942157, -0.42272749,  0.2997699 ],
       [ 0.2116478 , -0.37334889,  0.72831526,  1.48814284],
       [ 2.29669259, -2.10514137, -0.25655144,  0.87218259]])

In [178]:
arr > 0

array([[ True,  True, False, False],
       [False, False, False,  True],
       [ True, False,  True,  True],
       [ True, False, False,  True]])

In [179]:
np.where(arr > 0, 2, -2)

array([[ 2,  2, -2, -2],
       [-2, -2, -2,  2],
       [ 2, -2,  2,  2],
       [ 2, -2, -2,  2]])

In [180]:
np.where(arr > 0, 2, arr)

array([[ 2.        ,  2.        , -0.67364028, -0.00315331],
       [-0.0094574 , -0.10942157, -0.42272749,  2.        ],
       [ 2.        , -0.37334889,  2.        ,  2.        ],
       [ 2.        , -2.10514137, -0.25655144,  2.        ]])

#### Mathematical and Statistical